export const STORAGE_KEY_ORDER = "APART_TRADE_LIST_APP:ORDER";
export const STORAGE_KEY_FILTER = "APART_TRADE_LIST_APP:FILTER";
export const STORAGE_KEY_FAVORITE_LIST = "APART_TRADE_LIST_APP:FAVORITE_LIST";
export const STORAGE_KEY_APART_LIST = "APART_TRADE_LIST_APP:APART_LIST";
